// Variables con let//
//variables
let producto = 'Audifonos Gamer'; //nIniciar variable y signarle valor
let disponible; // Iniciamos la variable pero sin valor.
// producto = true;// reasignando el valor de la variable.
disponible = true;// reasignando el valor de la variable

let producto1 = 'Computadora',
    disponible1 = true,
    categoria = 'Computadoras';

//let 1disponible;// Las varibles no pueDen iniciar con numeros ni - pero si finalizar
let producto1;// Puede finalizar con numero
let _producto; //Si esta disponible//
//let produ-cto;// No esta Permitido
let produc_to;//Esta  permitido
let producto_;//Si esta Permitido

//Estilos para las variables

let nombre_proDucto = 'Monitor HD';
let nombreProrodducto = 'Monitor HD';
let NombreProducto = 'Monitor HD';
let nombreproducto = 'Monitor HD';

